name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  id-token: write  # Required for OpenID Connect (OIDC) authentication
  contents: read   # Required to read the repository content

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "0.4.15"
        
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
    
    - name: Install the project
      run: uv sync --all-extras
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip bump2version

    - name: Bump version
      run: |
        bump2version patch  # You can change this to minor or major based on the release type
    
    - name: Commit version bump
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Bump version for release"
        git push


    - name: Build package
      run: uv build


    - name: Publish to PyPI (via Trusted Publisher)
      env:
        TWINE_USERNAME: "dorokah"
        TWINE_PASSWORD: ${{ secrets.pypi_token }}
      run: uvx twine upload dist/*
